# Generated by Django 3.1.4 on 2020-12-25 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='owner_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='contact_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
